config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"  # Defines the root or entry point of the application

  get "password",to:"password#edit", as: :edit_password
  patch "password",to:"password#update",as: :update_password_path

  get "password/reset", to:"password_resets#new"
  post "password/reset", to:"password_resets#create"
  get "password/reset/edit", to:"password_resets#edit"
  post "password/reset/edit", to:"password_resets#update"


  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get 'sign_in',to:"session#new"
  post 'sign_in',to:"session#create"

  delete "logout", to: "session#destroy"  # Comma added here

  get "about", to: "about#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current<ActiveSupport::CurrentAttributes
  attribute:user
end

#In Ruby on Rails, ActiveSupport::CurrentAttributes is a special class that allows you to set and
#access global, thread-safe attributes. These attributes are specific to the current request or
#context, making them useful for things like storing the current user across different parts of
#your application.

#Example
# In a controller
#Current.user = @current_user

# In a model or another controller
#puts Current.user.name

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/user.rb
#email : string
#password_digest : string
#
#password:string:virtual
#password_confirmation:string:virtual
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: {
    with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
    message: "Invalid email format"
  }
end

app/controllers/about_controller.rb
class AboutController<ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action:set_current_user
# before_action :set_current_user:
#before_action is a Rails callback that runs a specified method before executing any action in the controller.

  def set_current_user
    if session[:user_id]
      Current.user=User.find_by(id:session[:user_id])
    end
  end

  #begin The ! at the end of the method name (require_user_logged_in!) suggests that this method performs
  # a critical or impactful action. It indicates that the method is enforcing a requirement or performing
  # an important check.
  def require_user_logged_in!
    redirect_to sign_in_path, alert: 'You must be signed in to do that.' if Current.user.nil?
  end

end

#the ? character is commonly used in method names to indicate that the method returns a boolean value,
#often answering a question about the state of the object. This is known as a predicate method.

=begin
1.
class Cart
  def empty?
    items.empty?
  end
end
empty?: Returns true if the items array is empty.

2.
class Article
  def published?
    !published_at.nil?
  end
end
published?: Returns true if the published_at attribute is not nil, indicating that the article has been
 published.

 3.
 class User
  def adult?
    age >= 18
  end
end
adult?: Returns true if the user's age is 18 or older.
=end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbs, :fats)
    end
end

app/controllers/main_controller.rb
class MainController<ApplicationController
  def index
  end
end

app/controllers/password_controller.rb
class PasswordController<ApplicationController
  before_action :require_user_logged_in!
  def edit

  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path ,notice:"Password updated"
    else
      render :edit
    end
  end

  def password_params
    params.require(:user).permit(:password,:password_confirmation)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController<ApplicationController
  def new

  end

  def create
    @user=User.find_by(email:params[:email])
    if @user.present?
      puts 'here'
      PasswordMailer.with(user:@user).reset.deliver_now
    end
    redirect_to root_path,notice:"if an account with that email is found in our database, we have sent a link to reset your password"
  end

  def edit

  end

  def update

  end
end

app/controllers/registration_controller.rb
class RegistrationController<ApplicationController
  def new
    @user =User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to root_path,notice:"Successfully Created record"
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController<ApplicationController
  def new
  end

  def create
    user=User.find_by(email:params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id]=user.id
      redirect_to root_path,notice:"Logged In Successfully"
    else
      flash[:alert]="Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to root_path,notice:"Logged Out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Meal type:</strong>
    <%= entry.meal_type %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= entry.calories %>
  </p>

  <p>
    <strong>Proteins:</strong>
    <%= entry.proteins %>
  </p>

  <p>
    <strong>Carbs:</strong>
    <%= entry.carbs %>
  </p>

  <p>
    <strong>Fats:</strong>
    <%= entry.fats %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :meal_type, style: "display: block" %>
    <%= form.text_field :meal_type %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block" %>
    <%= form.number_field :calories %>
  </div>

  <div>
    <%= form.label :proteins, style: "display: block" %>
    <%= form.number_field :proteins %>
  </div>

  <div>
    <%= form.label :carbs, style: "display: block" %>
    <%= form.number_field :carbs %>
  </div>

  <div>
    <%= form.label :fats, style: "display: block" %>
    <%= form.number_field :fats %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title do%>
  Foodlog &ndash;<%DateTime.now%>
<%end%>

<div id="entries">
  <% @entries.each do |entry| %>
    <%= render entry %>
    <p>
      <%= link_to "Show this entry", entry %>
    </p>
  <% end %>
</div>

<%= link_to "New entry", new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", entries_path %>

  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# I have created this partial view
      have created a folder called shared and a file called _header.erb
      A partial view file name should start with an underscore (_header.erb )
     %>
    <%= render partial:"shared/navbar"%>
    <div class="container">
      <%= render partial:"shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
<h1>Welcome To Sceduled Tweets</h1>
</div>

app/views/password/edit.html.erb
<h1>Change Password</h1>

<%= form_with model: Current.user, url: edit_password_path do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "New password" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm new password" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Update Password", class: "btn btn-success" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password</h1>

<%=form_with url:password_reset_path do |form|%>
    <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "faisalinayath16@gmail.com" %>
    </div>
    <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-success" %>
  </div>
<%end%>

app/views/session/new.html.erb
<h1>Sign In</h1>

<%=form_with url:sign_in_path do |form|%>
   <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "faisalinayath16@gmail.com" %>
  </div>
  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    <%=link_to "Forgot Your Password?",password_reset_path%>
  </div>

  <div class="mb-3">
    <%= form.submit "Sign in", class: "btn btn-success" %>
  </div>
<% end%>

app/views/shared/_flash.html.erb
<%if flash[:notice]%>
    <div class="alert alert-info mt-4">
    <%=flash[:notice]%>
    </div>
<%end%>

<%if flash[:alert]%>
    <div class="alert alert-warning mt-4">
    <%=flash[:alert]%>
    </div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Navbar</a>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
    </ul>

    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user %>
        <li class="nav-item">
          <%=link_to Current.user.email,edit_password_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", sign_in_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>